#!/usr/bin/env python3
"""Generate the reassemblable disassembly (build/asm/code.s) with gbadisasm.

Seeds functions from:
  * fixed entry points (crt0, AgbMain, ...)
  * every Thumb BL target that starts with `push {..., lr}`
  * symbols/functions.csv (names are applied)
  * Thumb function pointers found in literal pools of a previous pass
    (iterated until no new functions appear)

The generated assembly is derived from the ROM, so it is written to build/
and never committed; the inputs (this script + symbols/) are the source of truth.
"""
import csv
import os
import re
import subprocess
import sys

from romlib import ROOT, baserom_path, load_rom, u16

CODE_END = 0x0824DAFA  # first byte after the last function (verified by rebuild)
GBADISASM = os.environ.get("GBADISASM", os.path.join(ROOT, "build", "tools", "gbadisasm", "gbadisasm"))

FIXED = [
    ("arm_func", 0x080001B4, "crt0_Init"),
    ("arm_func", 0x080001F0, "IntrMain"),  # copied to IWRAM 0x03003A60
    ("thumb_func", 0x0800145C, "AgbMain"),
]
# ROM ranges that are code linked elsewhere (IWRAM overlays): emit as data
OVERLAYS = [
    (0x08000350, 0x0800145C, "iwram_code_03000000"),
    (0x0822F248, 0x0822F648, "m4a_SoundMainRAM_030035F0"),
]


def load_names():
    names = {}
    p = os.path.join(ROOT, "symbols", "functions.csv")
    if os.path.exists(p):
        for r in csv.DictReader(open(p)):
            names[int(r["addr"], 16)] = r
    return names


def bl_targets(b):
    seeds = set()
    for o in range(0, CODE_END - 0x08000000, 2):
        h1, h2 = u16(b, o), u16(b, o + 2)
        if (h1 & 0xF800) == 0xF000 and (h2 & 0xF800) == 0xF800:
            off11 = h1 & 0x7FF
            if off11 & 0x400:
                off11 -= 0x800
            t = o + 4 + (off11 << 12) + ((h2 & 0x7FF) << 1)
            if 0 <= t < CODE_END - 0x08000000 and (u16(b, t) & 0xFF00) == 0xB500:
                seeds.add(0x08000000 + t)
    return seeds


def plausible_entry(b, a):
    """A pointer-derived Thumb entry must look like a function start: a push,
    or directly after a return / alignment padding."""
    o = a - 0x08000000
    h = u16(b, o)
    if (h & 0xFE00) == 0xB400:  # push {...} / push {..., lr}
        return True
    prev = u16(b, o - 2)
    prev2 = u16(b, o - 4)
    return (prev & 0xFF80) == 0x4700 or (prev & 0xFF00) == 0xBD00 or prev == 0 or \
        (prev2 & 0xFF80) == 0x4700 and prev == 0x0000


def in_overlay(a):
    return any(s <= a < e for s, e, _ in OVERLAYS)


def write_cfg(path, seeds, names):
    lines = ["# generated by tools/disasm.py -- edit symbols/functions.csv instead"]
    fixed = {a for _, a, _ in FIXED}
    for kind, a, n in FIXED:
        lines.append(f"{kind} {a:#x} {n} f")
    for s, e, n in OVERLAYS:
        lines.append(f"data_label {s:#x}")
    for a in sorted(seeds - fixed):
        if in_overlay(a):
            continue
        r = names.get(a)
        if r and r.get("mode") == "arm":
            lines.append(f"arm_func {a:#x} {r['name']}")
        else:
            lines.append(f"thumb_func {a:#x}" + (f" {r['name']}" if r else ""))
    open(path, "w").write("\n".join(lines) + "\n")


def run(cfg):
    r = subprocess.run([GBADISASM, baserom_path(), "-c", cfg], check=True,
                       capture_output=True, text=True)
    for line in r.stderr.splitlines():
        print("gbadisasm:", line, file=sys.stderr)
    return r.stdout


def main():
    if not os.path.exists(GBADISASM):
        sys.exit(f"gbadisasm not found at {GBADISASM}; run tools/setup.sh")
    b = load_rom()
    names = load_names()
    seeds = bl_targets(b) | set(names)
    outdir = os.path.join(ROOT, "build", "asm")
    os.makedirs(outdir, exist_ok=True)
    cfg = os.path.join(outdir, "disasm.cfg")
    for it in range(6):
        write_cfg(cfg, seeds, names)
        asm = run(cfg)
        ptrs = {int(v, 16) for v in re.findall(r"\.4byte 0x(08[0-9A-F]{6})", asm)}
        new = {p & ~1 for p in ptrs if p & 1 and p < CODE_END} - seeds
        new = {a for a in new if not in_overlay(a) and plausible_entry(b, a)}
        nfunc = asm.count("func_start")
        print(f"pass {it}: {nfunc} functions, {len(new)} new pointer-derived seeds", file=sys.stderr)
        if not new:
            break
        seeds |= new
    open(os.path.join(outdir, "code.s"), "w").write(asm)


if __name__ == "__main__":
    main()
